### ISSUE TITLE
Support for Sandbox environment

### ISSUE THREAD

**Issue by rofokken** [jacobdekeizer/statusweb-client#2]
Hello Jacob,

I need to implement a connection to status web for our customer. Your library looks great and easy to implement. But when i checked the statusweb api manual it offers a diffent soap client wsdl (https://www.statusweb.nl/StatuswebAPIv4/Service.wso?WSDL) instead of the one you are using (https://www.statusweb.nl/statusXML/service.wso?WSDL). Also authentication is done very differently (session based). Is your library still good to use or should i implement my own implementation on the new soap wsdl endpoint (which has a sandbox environment)

Thank you for your contribution with this library and hope to hear from you soon.

Regards,

Robert

**Comment by jacobdekeizer** [comment]
Hi Robert,

I still use this version today without any problems. This version does not support sandbox, I got test API keys from statusweb through my carrier. If I have time I will make a version 2 with the new api version :)

**Comment by rofokken** [comment]
Hi Jacob, 

Thanks for your response, i implemented the new soap endpoints. These have support for sandbox environment based on api keys.

Regards,

Robert
